// Code generated by protoc-gen-go.
// source: msg2.proto
// DO NOT EDIT!

/*
Package ProtoTest is a generated protocol buffer package.

It is generated from these files:
	msg2.proto

It has these top-level messages:
	SkillInfo
	BulletBorn
	BulletMove
	AttackAction
	Hit
	PlayerInfo
	ObjInfo
	SkillObjInfo
	CredentialInfo
	FrameInfo
*/
package ProtoTest

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SkillInfo struct {
	Pid     int32 `protobuf:"varint,1,opt,name=pid" json:"pid,omitempty"`
	Skillid int32 `protobuf:"varint,2,opt,name=skillid" json:"skillid,omitempty"`
}

func (m *SkillInfo) Reset()                    { *m = SkillInfo{} }
func (m *SkillInfo) String() string            { return proto.CompactTextString(m) }
func (*SkillInfo) ProtoMessage()               {}
func (*SkillInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SkillInfo) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *SkillInfo) GetSkillid() int32 {
	if m != nil {
		return m.Skillid
	}
	return 0
}

type BulletBorn struct {
	Id float32 `protobuf:"fixed32,1,opt,name=id" json:"id,omitempty"`
	X  float32 `protobuf:"fixed32,2,opt,name=x" json:"x,omitempty"`
	Y  float32 `protobuf:"fixed32,3,opt,name=y" json:"y,omitempty"`
	Z  float32 `protobuf:"fixed32,4,opt,name=z" json:"z,omitempty"`
	V  float32 `protobuf:"fixed32,5,opt,name=v" json:"v,omitempty"`
}

func (m *BulletBorn) Reset()                    { *m = BulletBorn{} }
func (m *BulletBorn) String() string            { return proto.CompactTextString(m) }
func (*BulletBorn) ProtoMessage()               {}
func (*BulletBorn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BulletBorn) GetId() float32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BulletBorn) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *BulletBorn) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *BulletBorn) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *BulletBorn) GetV() float32 {
	if m != nil {
		return m.V
	}
	return 0
}

type BulletMove struct {
	Id      float32 `protobuf:"fixed32,1,opt,name=id" json:"id,omitempty"`
	X       float32 `protobuf:"fixed32,2,opt,name=x" json:"x,omitempty"`
	Y       float32 `protobuf:"fixed32,3,opt,name=y" json:"y,omitempty"`
	Z       float32 `protobuf:"fixed32,4,opt,name=z" json:"z,omitempty"`
	V       float32 `protobuf:"fixed32,5,opt,name=v" json:"v,omitempty"`
	Deleted bool    `protobuf:"varint,6,opt,name=deleted" json:"deleted,omitempty"`
}

func (m *BulletMove) Reset()                    { *m = BulletMove{} }
func (m *BulletMove) String() string            { return proto.CompactTextString(m) }
func (*BulletMove) ProtoMessage()               {}
func (*BulletMove) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BulletMove) GetId() float32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BulletMove) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *BulletMove) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *BulletMove) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *BulletMove) GetV() float32 {
	if m != nil {
		return m.V
	}
	return 0
}

func (m *BulletMove) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type AttackAction struct {
	Pid int32 `protobuf:"varint,1,opt,name=pid" json:"pid,omitempty"`
}

func (m *AttackAction) Reset()                    { *m = AttackAction{} }
func (m *AttackAction) String() string            { return proto.CompactTextString(m) }
func (*AttackAction) ProtoMessage()               {}
func (*AttackAction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AttackAction) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

type Hit struct {
	HitHp int32 `protobuf:"varint,1,opt,name=hitHp" json:"hitHp,omitempty"`
	Pid   int32 `protobuf:"varint,2,opt,name=pid" json:"pid,omitempty"`
}

func (m *Hit) Reset()                    { *m = Hit{} }
func (m *Hit) String() string            { return proto.CompactTextString(m) }
func (*Hit) ProtoMessage()               {}
func (*Hit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Hit) GetHitHp() int32 {
	if m != nil {
		return m.HitHp
	}
	return 0
}

func (m *Hit) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

type PlayerInfo struct {
	Pid  int32   `protobuf:"varint,1,opt,name=pid" json:"pid,omitempty"`
	X    float32 `protobuf:"fixed32,2,opt,name=x" json:"x,omitempty"`
	Y    float32 `protobuf:"fixed32,3,opt,name=y" json:"y,omitempty"`
	Z    float32 `protobuf:"fixed32,4,opt,name=z" json:"z,omitempty"`
	V    float32 `protobuf:"fixed32,5,opt,name=v" json:"v,omitempty"`
	Dead bool    `protobuf:"varint,6,opt,name=dead" json:"dead,omitempty"`
}

func (m *PlayerInfo) Reset()                    { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()               {}
func (*PlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PlayerInfo) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *PlayerInfo) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *PlayerInfo) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *PlayerInfo) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *PlayerInfo) GetV() float32 {
	if m != nil {
		return m.V
	}
	return 0
}

func (m *PlayerInfo) GetDead() bool {
	if m != nil {
		return m.Dead
	}
	return false
}

type ObjInfo struct {
	Id      int32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	X       float32 `protobuf:"fixed32,2,opt,name=x" json:"x,omitempty"`
	Y       float32 `protobuf:"fixed32,3,opt,name=y" json:"y,omitempty"`
	Z       float32 `protobuf:"fixed32,4,opt,name=z" json:"z,omitempty"`
	V       float32 `protobuf:"fixed32,5,opt,name=v" json:"v,omitempty"`
	Deleted bool    `protobuf:"varint,6,opt,name=deleted" json:"deleted,omitempty"`
}

func (m *ObjInfo) Reset()                    { *m = ObjInfo{} }
func (m *ObjInfo) String() string            { return proto.CompactTextString(m) }
func (*ObjInfo) ProtoMessage()               {}
func (*ObjInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ObjInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ObjInfo) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *ObjInfo) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *ObjInfo) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *ObjInfo) GetV() float32 {
	if m != nil {
		return m.V
	}
	return 0
}

func (m *ObjInfo) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type SkillObjInfo struct {
	Id      int32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	X       float32 `protobuf:"fixed32,2,opt,name=x" json:"x,omitempty"`
	Y       float32 `protobuf:"fixed32,3,opt,name=y" json:"y,omitempty"`
	Z       float32 `protobuf:"fixed32,4,opt,name=z" json:"z,omitempty"`
	V       float32 `protobuf:"fixed32,5,opt,name=v" json:"v,omitempty"`
	Deleted bool    `protobuf:"varint,6,opt,name=deleted" json:"deleted,omitempty"`
}

func (m *SkillObjInfo) Reset()                    { *m = SkillObjInfo{} }
func (m *SkillObjInfo) String() string            { return proto.CompactTextString(m) }
func (*SkillObjInfo) ProtoMessage()               {}
func (*SkillObjInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SkillObjInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SkillObjInfo) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *SkillObjInfo) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *SkillObjInfo) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *SkillObjInfo) GetV() float32 {
	if m != nil {
		return m.V
	}
	return 0
}

func (m *SkillObjInfo) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type CredentialInfo struct {
	Cre string `protobuf:"bytes,1,opt,name=cre" json:"cre,omitempty"`
}

func (m *CredentialInfo) Reset()                    { *m = CredentialInfo{} }
func (m *CredentialInfo) String() string            { return proto.CompactTextString(m) }
func (*CredentialInfo) ProtoMessage()               {}
func (*CredentialInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CredentialInfo) GetCre() string {
	if m != nil {
		return m.Cre
	}
	return ""
}

type FrameInfo struct {
	NewPlayer       []*PlayerInfo   `protobuf:"bytes,1,rep,name=newPlayer" json:"newPlayer,omitempty"`
	PlayerMove      []*PlayerInfo   `protobuf:"bytes,2,rep,name=playerMove" json:"playerMove,omitempty"`
	PlayerDead      []*PlayerInfo   `protobuf:"bytes,3,rep,name=playerDead" json:"playerDead,omitempty"`
	AttackAction    []*AttackAction `protobuf:"bytes,4,rep,name=attackAction" json:"attackAction,omitempty"`
	Hit             []*Hit          `protobuf:"bytes,5,rep,name=hit" json:"hit,omitempty"`
	SkillPrepare    []*SkillInfo    `protobuf:"bytes,6,rep,name=skillPrepare" json:"skillPrepare,omitempty"`
	SkillCancel     []*SkillInfo    `protobuf:"bytes,7,rep,name=skillCancel" json:"skillCancel,omitempty"`
	SkillStartUp    []*SkillInfo    `protobuf:"bytes,8,rep,name=skillStartUp" json:"skillStartUp,omitempty"`
	PlayerRelife    []*PlayerInfo   `protobuf:"bytes,9,rep,name=playerRelife" json:"playerRelife,omitempty"`
	ObjBorn         []*ObjInfo      `protobuf:"bytes,10,rep,name=objBorn" json:"objBorn,omitempty"`
	ObjMove         []*ObjInfo      `protobuf:"bytes,11,rep,name=objMove" json:"objMove,omitempty"`
	ObjDeleted      []*ObjInfo      `protobuf:"bytes,12,rep,name=objDeleted" json:"objDeleted,omitempty"`
	SkillObjBorn    []*SkillObjInfo `protobuf:"bytes,13,rep,name=skillObjBorn" json:"skillObjBorn,omitempty"`
	SkillObjMove    []*SkillObjInfo `protobuf:"bytes,14,rep,name=skillObjMove" json:"skillObjMove,omitempty"`
	SkillObjDeleted []*SkillObjInfo `protobuf:"bytes,15,rep,name=skillObjDeleted" json:"skillObjDeleted,omitempty"`
}

func (m *FrameInfo) Reset()                    { *m = FrameInfo{} }
func (m *FrameInfo) String() string            { return proto.CompactTextString(m) }
func (*FrameInfo) ProtoMessage()               {}
func (*FrameInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *FrameInfo) GetNewPlayer() []*PlayerInfo {
	if m != nil {
		return m.NewPlayer
	}
	return nil
}

func (m *FrameInfo) GetPlayerMove() []*PlayerInfo {
	if m != nil {
		return m.PlayerMove
	}
	return nil
}

func (m *FrameInfo) GetPlayerDead() []*PlayerInfo {
	if m != nil {
		return m.PlayerDead
	}
	return nil
}

func (m *FrameInfo) GetAttackAction() []*AttackAction {
	if m != nil {
		return m.AttackAction
	}
	return nil
}

func (m *FrameInfo) GetHit() []*Hit {
	if m != nil {
		return m.Hit
	}
	return nil
}

func (m *FrameInfo) GetSkillPrepare() []*SkillInfo {
	if m != nil {
		return m.SkillPrepare
	}
	return nil
}

func (m *FrameInfo) GetSkillCancel() []*SkillInfo {
	if m != nil {
		return m.SkillCancel
	}
	return nil
}

func (m *FrameInfo) GetSkillStartUp() []*SkillInfo {
	if m != nil {
		return m.SkillStartUp
	}
	return nil
}

func (m *FrameInfo) GetPlayerRelife() []*PlayerInfo {
	if m != nil {
		return m.PlayerRelife
	}
	return nil
}

func (m *FrameInfo) GetObjBorn() []*ObjInfo {
	if m != nil {
		return m.ObjBorn
	}
	return nil
}

func (m *FrameInfo) GetObjMove() []*ObjInfo {
	if m != nil {
		return m.ObjMove
	}
	return nil
}

func (m *FrameInfo) GetObjDeleted() []*ObjInfo {
	if m != nil {
		return m.ObjDeleted
	}
	return nil
}

func (m *FrameInfo) GetSkillObjBorn() []*SkillObjInfo {
	if m != nil {
		return m.SkillObjBorn
	}
	return nil
}

func (m *FrameInfo) GetSkillObjMove() []*SkillObjInfo {
	if m != nil {
		return m.SkillObjMove
	}
	return nil
}

func (m *FrameInfo) GetSkillObjDeleted() []*SkillObjInfo {
	if m != nil {
		return m.SkillObjDeleted
	}
	return nil
}

func init() {
	proto.RegisterType((*SkillInfo)(nil), "ProtoTest.SkillInfo")
	proto.RegisterType((*BulletBorn)(nil), "ProtoTest.BulletBorn")
	proto.RegisterType((*BulletMove)(nil), "ProtoTest.BulletMove")
	proto.RegisterType((*AttackAction)(nil), "ProtoTest.AttackAction")
	proto.RegisterType((*Hit)(nil), "ProtoTest.Hit")
	proto.RegisterType((*PlayerInfo)(nil), "ProtoTest.PlayerInfo")
	proto.RegisterType((*ObjInfo)(nil), "ProtoTest.ObjInfo")
	proto.RegisterType((*SkillObjInfo)(nil), "ProtoTest.SkillObjInfo")
	proto.RegisterType((*CredentialInfo)(nil), "ProtoTest.CredentialInfo")
	proto.RegisterType((*FrameInfo)(nil), "ProtoTest.FrameInfo")
}

func init() { proto.RegisterFile("msg2.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 518 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x95, 0xcd, 0x6e, 0xda, 0x40,
	0x10, 0xc7, 0x65, 0x1b, 0x43, 0x3c, 0xb8, 0xa4, 0x5a, 0xa5, 0xea, 0x1e, 0x2d, 0x9f, 0x38, 0xb4,
	0x1c, 0x88, 0xfa, 0xa5, 0x9e, 0x48, 0xa2, 0x8a, 0x1e, 0xaa, 0xa2, 0x4d, 0xfa, 0x00, 0x06, 0x4f,
	0x9a, 0x05, 0xc7, 0xb6, 0xcc, 0x96, 0x86, 0xbc, 0x5d, 0xdf, 0xac, 0xda, 0xb1, 0x8d, 0x97, 0x46,
	0x71, 0x51, 0xd5, 0xf6, 0xc4, 0xfe, 0xd9, 0xdf, 0xdf, 0x33, 0x9e, 0x0f, 0x00, 0xb8, 0x5d, 0x7f,
	0x1d, 0x8f, 0xf2, 0x22, 0x53, 0x19, 0xf3, 0x66, 0xfa, 0xe3, 0x0a, 0xd7, 0x2a, 0x7c, 0x03, 0xde,
	0xe5, 0x4a, 0x26, 0xc9, 0xc7, 0xf4, 0x3a, 0x63, 0x4f, 0xc1, 0xc9, 0x65, 0xcc, 0xad, 0xc0, 0x1a,
	0xba, 0x42, 0x1f, 0x19, 0x87, 0xde, 0x5a, 0x5f, 0xcb, 0x98, 0xdb, 0xf4, 0x6d, 0x2d, 0xc3, 0x2b,
	0x80, 0xb3, 0x6f, 0x49, 0x82, 0xea, 0x2c, 0x2b, 0x52, 0x36, 0x00, 0xbb, 0x32, 0xda, 0xc2, 0x96,
	0x31, 0xf3, 0xc1, 0xba, 0x23, 0x87, 0x2d, 0xac, 0x3b, 0xad, 0xb6, 0xdc, 0x29, 0xd5, 0x56, 0xab,
	0x7b, 0xde, 0x29, 0xd5, 0xbd, 0x56, 0x1b, 0xee, 0x96, 0x6a, 0x13, 0xa6, 0xf5, 0x53, 0x3f, 0x65,
	0x1b, 0xfc, 0x5b, 0x4f, 0xd5, 0x6f, 0x11, 0x63, 0x82, 0x0a, 0x63, 0xde, 0x0d, 0xac, 0xe1, 0x91,
	0xa8, 0x65, 0x18, 0x80, 0x3f, 0x51, 0x2a, 0x5a, 0xac, 0x26, 0x0b, 0x25, 0xb3, 0xf4, 0x61, 0x05,
	0xc2, 0x97, 0xe0, 0x4c, 0xa5, 0x62, 0x27, 0xe0, 0xde, 0x48, 0x35, 0xcd, 0xab, 0xab, 0x52, 0xd4,
	0xb8, 0xdd, 0xe0, 0x4b, 0x80, 0x59, 0x12, 0x6d, 0xb1, 0x78, 0xa4, 0xa0, 0x7f, 0xfa, 0x0a, 0x0c,
	0x3a, 0x31, 0x46, 0x75, 0xfe, 0x74, 0x0e, 0x57, 0xd0, 0xfb, 0x3c, 0x5f, 0x52, 0xa0, 0xa6, 0x52,
	0xee, 0x3f, 0xaa, 0x54, 0x0e, 0x3e, 0x0d, 0xca, 0xff, 0x8b, 0x18, 0xc2, 0xe0, 0xbc, 0xc0, 0x18,
	0x53, 0x25, 0xa3, 0xdd, 0x7c, 0x2e, 0x0a, 0xa4, 0xa0, 0x9e, 0xd0, 0xc7, 0xf0, 0x47, 0x17, 0xbc,
	0x0f, 0x45, 0x74, 0x8b, 0x74, 0x7f, 0x0a, 0x5e, 0x8a, 0xdf, 0xcb, 0xfa, 0x73, 0x2b, 0x70, 0x86,
	0xfd, 0xf1, 0xb3, 0xd1, 0x6e, 0xd6, 0x47, 0x4d, 0x63, 0x44, 0xc3, 0xb1, 0x57, 0x00, 0x39, 0x9d,
	0xf4, 0xc8, 0x71, 0xbb, 0xcd, 0x65, 0x80, 0x8d, 0xed, 0x42, 0xb7, 0xc5, 0x39, 0xc0, 0xa6, 0x41,
	0xf6, 0x1e, 0xfc, 0xc8, 0x18, 0x38, 0xde, 0x21, 0xe3, 0x73, 0xc3, 0x68, 0xce, 0xa3, 0xd8, 0x83,
	0x59, 0x00, 0xce, 0x8d, 0x54, 0xdc, 0x25, 0xcf, 0xc0, 0xf0, 0x4c, 0xa5, 0x12, 0xfa, 0x8a, 0xbd,
	0x05, 0x9f, 0x16, 0x74, 0x56, 0x60, 0x1e, 0x15, 0xc8, 0xbb, 0x84, 0x9e, 0x18, 0xe8, 0x6e, 0xdb,
	0xc5, 0x1e, 0xc9, 0x5e, 0x43, 0x9f, 0xf4, 0x79, 0x94, 0x2e, 0x30, 0xe1, 0xbd, 0x16, 0xa3, 0x09,
	0xee, 0x22, 0x5e, 0xaa, 0xa8, 0x50, 0x5f, 0x72, 0x7e, 0xf4, 0xdb, 0x88, 0x15, 0xc9, 0xde, 0x81,
	0x5f, 0x16, 0x46, 0x60, 0x22, 0xaf, 0x91, 0x7b, 0x6d, 0x35, 0xdc, 0x43, 0xd9, 0x0b, 0xe8, 0x65,
	0xf3, 0xa5, 0xfe, 0xe5, 0xe1, 0x40, 0x2e, 0x66, 0xb8, 0xaa, 0x09, 0x15, 0x35, 0x52, 0xd1, 0xd4,
	0xde, 0x7e, 0x2b, 0x4d, 0x8d, 0x1d, 0x03, 0x64, 0xf3, 0xe5, 0x45, 0x35, 0x93, 0xfe, 0xa3, 0x06,
	0x83, 0xd2, 0x5d, 0x5d, 0x57, 0xcb, 0x41, 0x49, 0x3d, 0x79, 0xd0, 0x55, 0x73, 0x77, 0xc4, 0x1e,
	0x6c, 0x9a, 0x29, 0xc7, 0xc1, 0x81, 0x66, 0xca, 0x76, 0x02, 0xc7, 0xb5, 0xae, 0x53, 0x3e, 0x6e,
	0xf7, 0xff, 0xca, 0xcf, 0xbb, 0xf4, 0xa7, 0x70, 0xfa, 0x33, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x0a,
	0x2f, 0xb1, 0x22, 0x06, 0x00, 0x00,
}
